import jsx from "eleventy-hast-jsx";
const { Raw, DOCTYPE, Comment } = jsx;

// CSS class helper, usage like className={classes(foo)}, will omit attribute if list is empty
const classes = (classes) => classes.join(" ") || undefined

// this does not work
import {format} from 'hast-util-format'
const doFormat = true;
const postprocess = (tree) => { if(doFormat) format(tree); return tree; }

import eleventyNavigationPlugin from "@11ty/eleventy-navigation";
// similar to filter; https://github.com/11ty/eleventy-navigation/blob/main/.eleventy.js#L12
const eleventyNavigation = eleventyNavigationPlugin.navigation.find;

const Navigation = ({ data }) => {
  //debugger;
  const navPages = eleventyNavigation(data.collections.all, "tour");
  const currentUrl = data.permalink;
    
  const renderNavListItem = (entry, level) => {
    const isActive = entry.url === currentUrl;
    const hasChildren = entry.children && entry.children.length > 0;
    const liClasses = entry.data.nav_class || [];
    if(isActive) liClasses.push("active");
    var aTitle = entry.data.title;
    if(aTitle == entry.title) aTitle = undefined;

    return (
      <li key={entry.key} className={classes(liClasses)}>
        <a
          href={entry.url}
          data-id={entry.data.page_id}
          data-key={entry.key}
          title={aTitle}
        >
          {entry.title}
        </a>
        {hasChildren && (
          <ul className={`u${level}`}>
            {entry.children.map(child => renderNavListItem(child, level + 1))}
          </ul>
        )}
      </li>
    );
  };

  return (
    <ul className="u1">
      {navPages.map(entry => renderNavListItem(entry, 2))}
    </ul>
  );
};

export default ({msg, ...data}) => {

// TODO: Should define a proper set of variables to be transfered to client
    
const bodyClasses = [
    "lang-" + data.lang,
    "page-" + data.page_id,
    // still missing:
    // in-nav => seite_in_nav
    // in- => seite_in_ul
    
    "design-2017-06-26" // legacy
]

// still missing: pagecss (conditional css per page)

const urlprefix_lang = `/${data.lang}`;

return postprocess(<>
<DOCTYPE />
<Comment>
 Achtung, diese Datei ist automatisch GENERIERT.
 Alle Änderungen an dieser Datei werden ÜBERSCHRIEBEN!
 Attention, this file is automatically GENERATED.
 Any edits to this file will be OVERWRITTEN.
</Comment>
<html class="no-js" lang={data.lang}>
<head>
	<meta charset="utf-8" />
	<title>{data.html_title}</title>
	<meta name="author" content="technikum29-Team" />
	<meta name="generator" content={`t29v8/${data.eleventy.generator}`} />
	<meta name="t29.cachedate" content={data.html_time} />
	<meta name="t29.page_id" content={data.page_id} />
	
	{data.header_prepend?.map(header => <Raw html={header} />)}

	<Comment> t29v6 template.php has a ton of other stuff here, amongst others:
		logic for passing data to client side JS, apple logos,
		links for RSS, interlanguage, JS, CSS </Comment>

	<link rel="copyright" href={urlprefix_lang+msg('footer-legal-file')} title={msg('footer-legal-link')} />
	<link rel="alternate" type="application/rss+xml" href={urlprefix_lang+"/news.rss"} title={msg('rss-title')} />
	<link rel="apple-touch-icon" type="image/x-icon" href="/shared/img-v6/touch-icon.png" />
	<meta name="viewport" content="width=device-width,initial-scale=1" />

	<script src="/shared/js-v6/libs/modernizr-2.0.6.min.js"></script>{/* probably no more neccessary */}
</head>
<body className={classes(bodyClasses)}>
	<div id="container">
		<h1 role="banner"><a href="/" title={msg('head-h1-title')}>{msg('head-h1')}</a></h1>
		<div id="background-color-container">
			<section class="main content" role="main" id="content">
				<Comment>
					<ul class="messages panel <?php if($this->log->is_empty()) echo 'empty'; ?> nolist">
					</ul>	
				</Comment>
				<Comment> *** Start of content *** </Comment>

				<Raw html={data.content} />
				
				<Comment> *** End of content *** </Comment>
			</section>
			<hr/>
			<section class="sidebar top">
					{/* Platz fuer eigentlich per "Extension" eingepflegtem Inhalt */}
					<Comment>
					<a class="button alertbox termine" href="/de/#termine">
						<strong>Aktuelle Termine</strong>
						
					</a>
					</Comment>
					
					<h2 class="visuallyhidden" id="tour-navigation">{msg("sidebar-h2-tour")}</h2>
					{data.sidebar_content ?
						<nav class="side contains-custom">{data.sidebar_content}</nav>
					:
						<nav class="side contains-menu">
							<Navigation data={data} />
						</nav>
					}
					<Comment>menu changing buttons are made with javascript</Comment>
			</section>
			<section class="sidebar bottom">
				<Comment>inhalte die unten ueber dem header sind</Comment>
			</section>
		</div>{/* #background-color-container */}
		<hr/>
		<header class="banner">
			<h2 class="visuallyhidden">{msg("sidebar-h2-mainnav")}</h2>
				<nav class="horizontal">
					{
						data.mainnav_content ?
							data.mainnav_content
						:
							"" /* print horizontal menu */
					}
				</nav>
				<nav class="top">
					<h3 class="visuallyhidden">{msg("sidebar-h2-lang")}</h3>
					<ul>
						{/* interlanguage links etc */}
					</ul>
					<form method="get" action={msg('topnav-search-page')}> {/* TODO: $href make relative Links! */}
						<span class="no-js">{msg('topnav-search-label')}:</span>
						<input type="text" value="" data-defaultvalue={msg('topnav-search-label')} name="q" class="text" />
						<input type="submit" value={msg('topnav-search-label')} class="button" />
					</form>
				</nav>
		</header>
		<hr/>
		<Comment>
			Weiter geht es hier mit Footer usw!
		</Comment>
	</div>{/* #container */}
</body>
</html>

{/* So long and thanks for all the */} </>);} /* fish! */
