import jsx from "eleventy-hast-jsx";
const { Raw, DOCTYPE, Comment } = jsx;

// CSS class helper, usage like className={classes(foo)}, will omit attribute if list is empty
const classes = (classes) => classes.join(" ") || undefined

// this does not work
import {format} from 'hast-util-format'
const doFormat = true;
const postprocess = (tree) => { if(doFormat) format(tree); return tree; }

const Navigation = ({ data, tree_name, baseClass="u1" }) => {
  //debugger;
  const navPages = data[tree_name];
  const currentUrl = data.permalink;
      
  const renderNavListItem = (entry, level) => {
    const isActive = entry.url === currentUrl;
    const hasChildren = entry.children && entry.children.length > 0;
    const liClasses = entry.data.nav_class || [];
    if(isActive) liClasses.push("active");
	const ariaCurrent = isActive ? "page" : undefined;
    var aTitle = entry.data.title;
    if(aTitle == entry.title) aTitle = undefined;

    return (
      <li key={entry.key} className={classes(liClasses)}>
        <a
          href={entry.url}
          data-id={entry.data.page_id}
          data-key={entry.key}
          title={aTitle}
          aria-current={ariaCurrent}
        >
          {entry.title}
        </a>
        {hasChildren && (
          <ul className={`u${level}`}>
            {entry.children.map(child => renderNavListItem(child, level + 1))}
          </ul>
        )}
      </li>
    );
  };

  return (
    <ul className={baseClass}>
      {navPages.map(entry => renderNavListItem(entry, 2))}
    </ul>
  );
};

export default ({msg, ...data}) => {

// TODO: Should define a proper set of variables to be transfered to client
	
const bodyClasses = [
    "lang-" + data.lang,
    "page-" + data.page_id,
    // still missing:
    // in-nav => seite_in_nav
    // in- => seite_in_ul
    
    "design-2017-06-26" // legacy
]

const client_js_transfer = Object.fromEntries(["lang", "seiten_id", "seite_in_nav", "seite_in_ul"].map(key => [key, data[key]]));

const urlprefix = "/";
const urlprefix_lang = urlprefix + data.lang;

return postprocess(<>
<DOCTYPE />
<Comment>
 Achtung, diese Datei ist automatisch GENERIERT.
 Alle Änderungen an dieser Datei werden ÜBERSCHRIEBEN!
 Attention, this file is automatically GENERATED.
 Any edits to this file will be OVERWRITTEN.
</Comment>
<html class="no-js" lang={data.lang}>
<head>
	<meta charset="utf-8" />
	<title>{data.html_title}</title>
	<meta name="author" content="technikum29-Team" />
	<meta name="generator" content={`t29v8/${data.eleventy.generator}`} />
	<meta name="t29.cachedate" content={data.html_time} />
	<meta name="t29.page_id" content={data.page_id} />
	
	{data.header_prepend?.map(header => <Raw html={header} />)}

	<Comment> t29v6 template.php has a ton of other stuff here, amongst others:
		logic for passing data to client side JS, apple logos,
		links for RSS, interlanguage, JS, CSS.
		
		Ausserdem wichtiges neues TODO: OG-Links!
	</Comment>

	<link rel="copyright" href={urlprefix_lang+msg('footer-legal-file')} title={msg('footer-legal-link')} />
	<link rel="alternate" type="application/rss+xml" href={urlprefix_lang+"/news.rss"} title={msg('rss-title')} />
	<link rel="apple-touch-icon" type="image/x-icon" href="/shared/img-v6/touch-icon.png" />
	<meta name="viewport" content="width=device-width,initial-scale=1" />
	
	<link rel="stylesheet" type="text/css" data-foo="bar" href={urlprefix+msg('bundle-css-path')} />
	{/* todo, resolve this promise */}
	{ data.page_css_file && <link rel="stylesheet" type="text/css" href={urlprefix+data.page_css_file} /> }

	<script src="/shared/js-v6/libs/modernizr-2.0.6.min.js"></script>{/* probably no more neccessary */}
</head>
<body className={classes(bodyClasses)}>
	<div id="container">
		<h1 role="banner"><a href="/" title={msg('head-h1-title')}>{msg('head-h1')}</a></h1>
		<div id="background-color-container">
			<section class="main content" role="main" id="content">
				<Comment>
					<ul class="messages panel <?php if($this->log->is_empty()) echo 'empty'; ?> nolist">
					</ul>	
				</Comment>
				<Comment> *** Start of content *** </Comment>

				<Raw html={data.content} />
				
				<Comment> *** End of content *** </Comment>
			</section>
			<hr/>
			<section class="sidebar top">
					{/* Platz fuer eigentlich per "Extension" eingepflegtem Inhalt */}
					<Comment>
					<a class="button alertbox termine" href="/de/#termine">
						<strong>Aktuelle Termine</strong>
					</a>
					</Comment>
					
					<p>Breadcrumbs:</p>
					<Navigation data={data} tree_name="nav_breadcrumbs" />
					
					
					<h2 class="visuallyhidden" id="tour-navigation">{msg("sidebar-h2-tour")}</h2>
					{data.sidebar_content ?
						<nav class="side contains-custom">{data.sidebar_content}</nav>
					:
						<nav class="side contains-menu">
							<Navigation data={data} tree_name="nav_main" />
						</nav>
					}
					<Comment>menu changing buttons are made with javascript</Comment>
			</section>
			<section class="sidebar bottom">
				<Comment>inhalte die unten ueber dem header sind</Comment>
			</section>
		</div>{/* #background-color-container */}
		<hr/>
		<header class="banner">
			<h2 class="visuallyhidden">{msg("sidebar-h2-mainnav")}</h2>
				<nav class="horizontal">
					{/* Pages with tag: nav_horizontal will get part of this navigation */}
					{
						data.mainnav_content
						?	data.mainnav_content
						:	<Navigation data={data} tree_name="nav_horizontal" />
					}
				</nav>
				<nav class="top">
					<h3 class="visuallyhidden">{msg("sidebar-h2-lang")}</h3>
					<ul>
						{/* interlanguage links etc */}
					</ul>
					<form method="get" action={msg('topnav-search-page')}> {/* TODO: $href make relative Links! */}
						<span class="no-js">{msg('topnav-search-label')}:</span>
						<input type="text" value="" data-defaultvalue={msg('topnav-search-label')} name="q" class="text" />
						<input type="submit" value={msg('topnav-search-label')} class="button" />
					</form>
				</nav>
		</header>
		<hr/>
		<Comment>
			Weiter geht es hier mit Footer usw!
		</Comment>
	</div><Comment> end of #container -- Note: #container geht for footer.attached zu.</Comment>
	{/* footer attached */}
	
	<script src="/shared/js-v6/libs/jquery-1.7.2.min.js"></script>
	<Raw html={`<script>window.t29={'conf': ${JSON.stringify(client_js_transfer)}};</script>`} />
	<script src={urlprefix+msg("bundle-js-path")}></script>
	{ data.page_js_file && <script src={urlprefix+data.page_js_file} /> }
    {/* Piwik Noscript, Script selbst wird asynchron im JS-Bereich aufgerufen */}
    <noscript><img src={msg("js-piwik-noscript-imgsrc")} alt="" /></noscript>
    <Raw html={data.body_append} />
</body>
</html>

{/* So long and thanks for all the */} </>);} /* fish! */
