#
# This works but is super slow. It needs about 8mins per run.
# Reason is the large repo, 5GB to fetch, 3GB artifacts.
#

name: Build Eleventy on Github

on:
  push:
    branches:
      - v8

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [23.x]
    steps:
      - name: Checkout (fast-forward fetch)
        run: |
          set -euo pipefail
          if [ -d .git ]; then
            git remote set-url origin https://github.com/${{ github.repository }}.git
            git fetch --prune --tags origin +${{ github.sha }}:${{ github.sha }}
            git checkout -f ${{ github.sha }}
          else
            git clone https://github.com/${{ github.repository }}.git .
            git checkout -f ${{ github.sha }}
          fi
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run npm (dep, build) with BUILD_PHP flag
        run: |
          npm ci
          BUILD_PHP=1 npm run build
      - name: Deploy locally
        with:
          publish_dir: ./_site
          host_dir: ${{ secrets.DEPLOY_LOCAL_HOST_DIR }}
        run: |
          cp -a ./_site/. /home/www-github-action/that-ooutput
      - uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: ./_site/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: sstc/rsync
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: static-site
          path: ./_site/
      - name: Prepare SSH remote access
        run: |
          SSHDIR=/root/.ssh # thanks to the crappy docker image
          mkdir -p $SSHDIR
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > $SSHDIR/id_rsa
          echo "${{ secrets.DEPLOY_SSH_KNOWN_HOST }}" > $SSHDIR/known_hosts
          chmod 0700 $SSHDIR && chmod 600 $SSHDIR/* 
          #id && stat $SSHDIR && ls -l $SSHDIR
      - name: Upload
        run: |
          rsync -avz ./_site/ ${{secrets.DEPLOY_SSH_USER}}@${{secrets.DEPLOY_SSH_HOST}}:${{secrets.DEPLOY_SSH_REMOTE_PATH}} \
